/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
	aws_project_region: "us-east-1",
	aws_cognito_identity_pool_id:
		"us-east-1:c3844f97-347a-46bd-abd7-3261b0304ef6",
	aws_cognito_region: "us-east-1",
	aws_user_pools_id: "us-east-1_RAVGttXKv",
	aws_user_pools_web_client_id: "14r50n5urkapn40i6e5d8gautc",
	oauth: {},
	aws_cognito_username_attributes: ["EMAIL"],
	aws_cognito_social_providers: [],
	aws_cognito_signup_attributes: [],
	aws_cognito_mfa_configuration: "OFF",
	aws_cognito_mfa_types: ["SMS"],
	aws_cognito_password_protection_settings: {
		passwordPolicyMinLength: 8,
		passwordPolicyCharacters: [
			"REQUIRES_LOWERCASE",
			"REQUIRES_NUMBERS",
			"REQUIRES_SYMBOLS",
			"REQUIRES_UPPERCASE",
		],
	},
	aws_cognito_verification_mechanisms: ["EMAIL"],
};

export default awsmobile;
